project:
  type: website

website:
  title: "The Heat is On!"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - about.qmd
      - text: Station
        href: Station/station.html
      - text: Proposal
        href: proposal/proposal.html
        

#format:
#  html:
#    theme: cosmo
#    css: styles.css
#    toc: true

# editor: visual

