project:
  type: website

website:
  #title: "<img src='images/logo.png' alt='The Heat is On!' />"
  title: "The Heat is On!"
  navbar:
    left:
      - text: Home
        href: index.qmd
        
      - text: Proposal
        href: proposal/proposal.html
        
      - text: Weather Station
        href: Station/station.html
        
      - text: Exploratory Data Analysis
        menu:
          - text: Data Preparation
            href: EDA/Data_Preparation.html
          - text: EDA - Temperature
            href: EDA/EDA-Temperature.html
          - text: EDA - Rainfall
            href: EDA/EDA-Rainfall.html   
      - text: Prototype
        menu: 
          - text: EDA - Geospatial Analysis
            href: Prototype/EDA-GeospatialAnalysis.html
          - text: EDA - Time Series Analysis
            href: Prototype/EDA-TimeSeriesAnalysis.html   
          - text: CDA
            href: Prototype/CDA.html
          - text: Forecast
            href: Prototype/Forecast.html
      - text: Poster
        href: Poster.html    
      - text: User Guide
        href: UserGuide.html
      - text: Shiny App
        href: https://chockwankee.shinyapps.io/Group11_VAP_ShinyApp_Windows/
        
        
page-footer:
    border: false
    background: transparent
    foreground: DimGray
    left: Left content
    right: Right content

format:
  html:
    theme: 
    - minty
    - minty_custom.scss
    css: styles.css
    toc: true

editor: visual

