project:
  type: website

website:
  title: "The Heat is On!"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Proposal
        href: proposal/proposal.html
      - text: Station
        href: Station/station.html
      - text: Rainfall
      - text: Temperature
      - text: Relative Humidity
      - text: Wind

format:
  html:
    theme: sketchy
    css: styles.css
    toc: true

editor: visual

