project:
  type: website

website:
  title: "Group11_VAP"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Station
        href: Station/station.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

