project:
  type: website

website:
  title: "The Heat is On!"
  navbar:
    left:
      - text: Home
        href: index.qmd
        
      - text: Proposal
        href: proposal/proposal.html
        
      - text: Station
        href: Station/station.html
        
      - text: Data Preparation
        href: EDA/Data_Preparation.html
        
      - text: Exploratory Data Analysis
        menu:
          - text: EDA_Noel
            href: EDA/EDA_Noel.html
          - text: EDA_Vanessa
            href: EDA/EDA_Vanessa.html
          - text: EDA_Wankee
            href: EDA/EDA_Wankee.html
      
      - text: Shiny App
        href: https://chockwankee.shinyapps.io/Group11_VAP_ShinyApp/

format:
  html:
    theme: sketchy
    css: styles.css
    toc: true

editor: visual

