---
title: "EDA_Wankee"
author: "Wan Kee"
date: "17 February 2024"
date-modified: "last-modified"
execute: 
  eval: true
  echo: true
  freeze: true
  warning: false
  message: false
  error: true
---

# 1. Import Packages

```{r}
pacman::p_load(tidyverse, readr, psych, st, stars, tmap)
```

```{r}
weather_list <- list.files(path = "data",
                           recursive = TRUE,
                           pattern = "\\.csv$",
                           full.names = TRUE)
list(weather_list)
```

```{r}
weather <- read_csv(weather_list)

weather <- weather %>%
  rename_with(~ gsub(" ", "_", .x), everything())

glimpse(weather)
```
```{r}
describe(weather)
```
::: {.callout-note collapse="true"}
## Save rds

```{r}
write_rds(weather, "data/weather.rds")
```
:::


::: {.callout-note collapse="true"}
## Load rds

```{r}
weather <- readRDS("data/weather.rds")
```
:::

```{r}
mpsz <- st_read(dsn = "data/geospatial", layer = "MPSZ-2019") %>% 
  st_transform(crs=3414)
```
```{r}
glimpse(mpsz)
```


```{r}
tmap_mode("view")

tm_shape(mpsz) +
  tm_polygons(col = "REGION_N", palette = "Set2")+
  tm_layout(main.title = "Planning Area",
            main.title.position = "left",
            main.title.size = 1,
            legend.show = FALSE,
            frame = FALSE) +
  tmap_options(check.and.fix = TRUE) +
  tm_view(set.zoom.limits = c(11,12))
```

```{r}
tmap_mode("view")

tm_shape(mpsz) +
  tm_polygons(col = "PLN_AREA_C", palette = "Set2")+
  tm_layout(main.title = "Planning Area",
            main.title.position = "left",
            main.title.size = 1,
            legend.show = FALSE,
            frame = FALSE) +
  tm_view(set.zoom.limits = c(11,12))
```

```{r}
tmap_mode("view")

tm_shape(mpsz) +
  tm_polygons(col = "SUBZONE_N", palette = "Set2")+
  tm_layout(main.title = "Planning Area",
            main.title.position = "left",
            main.title.size = 1,
            legend.show = FALSE,
            frame = FALSE) +
  tm_view(set.zoom.limits = c(11,12))
```


```{r}
unique(mpsz$PLN_AREA_N)
```

```{r}
unique(weather$Station)
```
```{r}
station_to_PA <- c(
  "Admiralty" = "WOODLANDS",
  "Ang Mo Kio" = "ANG MO KIO",
  "Boon Lay (East)" = "BOON LAY",
  "Changi" = "CHANGI",
  "Choa Chu Kang (South)" = "CHOA CHU KANG",
  "Clementi" = "CLEMENTI",
  "East Coast Parkway" = "BEDOK",
  "Jurong (West)" = "JURONG WEST",
  "Khatib" = "YISHUN",
  "Marina Barrage" = "DOWNTOWN CORE",
  "Newton" = "NEWTON",
  "Pasir Panjang" = "PASIR PANJANG",
  "Paya Lebar" = "PAYA LEBAR",
  "Seletar" = "SELETAR",
  "Sembawang" = "SEMBAWANG",
  "Tai Seng" = "HOUGANG",
  "Tengah" = "TENGAH",
  "Tuas South" = "TUAS"
)

weather$PA <- station_to_PA[weather$Station]
weather <- weather[, c("PA", setdiff(names(weather), "PA"))]
head(weather)
```


```{r}
weather <- weather %>%
  mutate_at(vars(Daily_Rainfall_Total,
                 Highest_30_Min_Rainfall,
                 Highest_60_Min_Rainfall,
                 Highest_120_Min_Rainfall,
                 Mean_Temperature,
                 Maximum_Temperature),
            as.numeric)
```
```{r}
weather$Daily_Rainfall_Total <- as.numeric(weather$Daily_Rainfall_Total)
weather$Highest_30_Min_Rainfall <- as.numeric(weather$Highest_30_Min_Rainfall)
weather$Highest_60_Min_Rainfall <- as.numeric(weather$Highest_60_Min_Rainfall)
weather$Highest_120_Min_Rainfall <- as.numeric(weather$Highest_120_Min_Rainfall)
weather$Mean_Temperature <- as.numeric(weather$Mean_Temperature)
weather$Maximum_Temperature <- as.numeric(weather$Maximum_Temperature)
weather$Minimum_Temperature <- as.numeric(weather$Minimum_Temperature)
```


```{r}
weather_map <- weather %>% 
  group_by(PA, Station, Year) %>% 
  summarise(Annual_Rainfall_Total = sum(Daily_Rainfall_Total, na.rm = TRUE),
            Annual_Highest_30_Min_Rainfall = sum(Highest_30_Min_Rainfall, na.rm = TRUE),
            Annual_Highest_60_Min_Rainfall = sum(Highest_60_Min_Rainfall, na.rm = TRUE),
            Annual_Highest_120_Min_Rainfall = sum(Highest_120_Min_Rainfall, na.rm = TRUE),
            Annual_Mean_Temperature = sum(Mean_Temperature, na.rm = TRUE),
            Annual_Maximum_Temperature = sum(Maximum_Temperature, na.rm = TRUE),
            Annual_Minimum_Temperature = sum(Minimum_Temperature, na.rm = TRUE)) %>%
  ungroup()

glimpse(weather_map)
```

```{r}
mpszweather <- left_join(mpsz, weather_map,
                         by = c("PLN_AREA_N" = "PA"))
glimpse(mpszweather)
```
```{r}
tm_shape(mpszweather) +
  tm_polygons(col = "Annual_Rainfall_Total", 
              palette = "Blues", 
              style = "jenks") +
  tm_view(set.zoom.limits = c(11,12))
```

```{r}
tm_shape(mpszweather) +
  tm_polygons(col = "Annual_Highest_30_Min_Rainfall", 
              palette = "Blues", 
              style = "jenks") +
  tm_view(set.zoom.limits = c(11,12))
```

```{r}
tm_shape(mpszweather) +
  tm_polygons(col = "Annual_Mean_Temperature", 
              palette = "Oranges", 
              style = "jenks") +
  tm_view(set.zoom.limits = c(11,12))
```

```{r}
tm_shape(mpszweather) +
  tm_polygons(col = "Annual_Maximum_Temperature", 
              palette = "Oranges", 
              style = "jenks") +
  tm_view(set.zoom.limits = c(11,12))
```

```{r}
tm_shape(mpszweather) +
  tm_polygons(col = "Annual_Minimum_Temperature", 
              palette = "Oranges", 
              style = "jenks") +
  tm_view(set.zoom.limits = c(11,12))
```

